<idv class="row">
    <div class="col-md-12">
    
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Konto zostało aktywowane</h3>
        </div>
        <div class="panel-body">
            <p>Witaj <?echo $user->name." ".$user->surname?></p>
            <p>Twoje konto zostało właśnie aktywowane.</p>
            <p>Możez się już <a href="<? echo $this->url('login')  ?>">zalogować</a></p>
        </div>
      </div>
    </div>
</idv>

