<div class="row">
    <div class="col-md-3 col-md-offset-4">
<div class="input-group">
<?php

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);
?>
<p class="text-center"><a href="<?php echo $this->url('login',array('action'=>'add'))?>">Nie masz konta?</a></p>
<p class="text-center"><a href="<?php echo $this->url('login',array('action'=>'remember'))?>">Zapomniałeś hasła?</a></p>
</div>
    </div>
</div>