<div class="row">
    <div class="col-md-3 col-md-offset-4">
<div class="input-group">

    
    <? if ($this->message) :?>
    
        <div class="alert alert-danger" style="text-align: center">
            <?php echo $this->message?>
        </div>

    <? endif; ?>
 <?php

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);
?>
    <p class="text-center">Zalogowanie się oznacza akcetację <a href="<?php echo $this->url('statute')?>">regulaminu</a></p>
<p class="text-center"><a href="<?php echo $this->url('login',array('action'=>'add'))?>">Nie masz konta?</a></p>
<p class="text-center"><a href="<?php echo $this->url('login',array('action'=>'remember'))?>">Zapomniałeś hasła?</a></p>
</div>
    </div>
</div>