<style>
    
    ul li {
        text-align: left;
        font-weight: bold;
    }
</style>
<div class="row">
<div class="col-md-4 col-md-offset-4">
<div class="input-group">

    
    <? if ($this->success) :?>
    
        <div class="alert alert-success" style="text-align: center">
            <p>Hasło zostało poprawnie zmiennione</p>
            <a href="<?echo $this->url('login')?>">Możesz się teraz zalogować</a>
            
        </div>

    <? endif; ?>

    
<?php
if (!$this->success)
{
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag($form);
}

?>
</div>
</div>
</div>