<idv class="row">
    <div class="col-md-12">
    
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Konto zostało utworzone</h3>
        </div>
        <div class="panel-body">
            <p>Witaj <?echo $user->name." ".$user->surname?></p>
            <p>Twoje konto zostało utworzone, ale nie jest jeszcze aktywne w naszym systemie.</p>
            <p>Na podany adres email - <?echo $user->email?> - została wysłana wiadomość z linkiem aktywacyjnym</p>
        </div>
      </div>
    </div>
</idv>
