<h1>Harmonogramy</h1>
<table class="table">
 <tr>
     <th>Id</th>
     <th>Data początku<span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
     <th>Data końca<span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
     <th>Operacje</th>
    
     
 </tr>
 <?php foreach ($schedulers as $schedule) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($schedule->id);?></td>
     <td><?php echo $this->escapeHtml($schedule->date_start);?></td>
     <td><?php echo $this->escapeHtml($schedule->date_end);?></td>
     <td>
          <?php if($this->session->role === 'admin') :?>
            <a href="<?php echo $this->url('scheduler',
             array('action'=>'delete', 'id' => $schedule->id));?>">Usuń</a>
            <?php endif ?>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

