 <?php
//var_dump($schedulers);
 $this->session = new \Zend\Session\Container('login');
 $title = 'Lista harmonogramów';
 $this->headTitle($title);



 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <form action="<?php echo $this->url('scheduler',array('action'=>'list'))?>" method="POST">
 <table class="table">
 <tr>
     <th>Lekarz <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
     <th>Początek grafiku <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="date_start"></th>
     <th>Koniec grafiku <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="date_end"></th>
         <th>Operacje </th>
 </tr>
 <?php  foreach ($schedulers as $val) :?>
 <tr>
     <td><?php echo $val->name ?></td>
     <td><?php echo $val->date_start ?></td>
     <td><?php echo $val->date_end ?></td>
     <?php if($this->session->role == 1) : ?>
     <td><a href="<?php echo $this->url('scheduler',
             array('action'=>'delete', 'id' => $val->id));?>">Usuń</a>  </td>
     <?php elseif ($this->session->role == 20) : ?>
     <td><a href="<?php echo $this->url('registration',
             array('action'=>'two',
                 'param' => date('Y-m-d',strtotime($val->date_start))));?>">Zapisz</a>  </td>
     <?php elseif (!$this->session->role) : ?>
     <td><a href="<?php echo $this->url('login');?>">Zaloguj się</a>  </td>
     <?php endif;?>
 </tr>
<?php  endforeach;?>
 </table>
 </form>
 <script type="text/javascript">
     $(document).ready(function() {
    $('.glyphicon').click(function(){   
       $('form').append('<input type="hidden" name="orderBy" value="'+$(this).attr('name')+'" />');
       $('form').append('<input type="hidden" name="physicianId" value="'+$('#sel1').val()+'" />');
       $('form').submit();
    });
    $('#sel1').change(function(){
            console.log($(this).val());
       $('form').append('<input type="hidden" name="physicianId" value="'+$(this).val()+'" />');
       $('form').submit();
    });
});
     
     
</script>