<?php echo $this->doctype(); ?>
<?php $this->session = new \Zend\Session\Container('login'); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
       <?php echo $this->headTitle('Super-Med Przychodnia') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/master.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<?php echo $this->home_active; ?>"><a href="<?php echo $this->url('home') ?>">Home</a></li>

                        <li class="<?php echo $this->registration_active; ?>"><a href="<?php echo $this->url('registration',array('action'=>'index')) ?>">Rezerwuj wizytę</a></li>
                        <li class="<?php echo $this->patientVisit_active; ?>"><a href="<?php echo $this->url('patient',array('action'=>'visit')) ?>">Moje wizyty</a></li>
                        <li class="<?php echo $this->user_active; ?>"><a href="<?php echo $this->url('user',array('action'=>'edit')) ?>">Edycja danych</a></li>
                        
                       
                        <?php if($this->session->login) :?>
                        <li><a href="<?php echo $this->url('login',array('action'=>'logout')) ?>">Wyloguj</a></li>
                        <?php else :?>
                        <li><a href="<?php echo $this->url('login',array('action'=>'login')) ?>">Zaloguj</a></li>
                        <?php endif;?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <a href='<?php echo $this->url('home')?>'><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Zend Framework 2" class="center-block" style="padding-bottom: 25px"/></a>
            <?php if($this->session->login) :?>
            <div style="display: block;text-align: right"> Witaj <?php echo $this->session->name ?></div>
            <?php endif;?>
            <?php echo $this->content; ?>
            <hr>
           <footer>
                <p>&copy;<?php echo date('Y') ?> by Krzysztof Malara WSTI <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
