<div class="row">
    <div class="col-md-4 col-md-offset-4">
        

<?php
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('physician'));
echo $this->formRow($form->get('specialization'));
echo $this->formRow($form->get('description'));
echo $this->formFile($form->get('image-file'));?><br />
<?echo $this->formRow($form->get('submit'));

echo $this->form()->closeTag($form);
?>
    </div>
</div>
