<?php
$this->session = new \Zend\Session\Container('login');
echo $this->form()->openTag($form);


   echo $this->formRow($form->get('name'));
   echo $this->formRow($form->get('surname'));
   echo $this->formRow($form->get('login'));
   echo $this->formRow($form->get('password'));
   echo $this->formRow($form->get('password-repeat'));
    if($this->session->role != 3)
    {
       echo $this->formRow($formPatient->get('pesel'));
    }
   echo $this->formRow($form->get('email'));
   echo $this->formRow($formPatient->get('birthday'));
   echo $this->formRow($formPatient->get('tel'));
   echo $this->formRow($form->get('submit'));


echo $this->form()->closeTag($form);

