<?php
$this->session = new \Zend\Session\Container('login');
echo $this->form()->openTag($form);


   echo $this->formRow($form->get('name'));
   echo $this->formRow($form->get('surname'));
   echo $this->formRow($form->get('login'));
   echo $this->formRow($form->get('password'));
   echo $this->formRow($form->get('password-repeat'));   
   echo $this->formRow($form->get('email'));
   echo $this->formRow($form->get('role'));
  
   if($formPatient)
    {
        echo $this->formRow($formPatient->get('birthday'));
        echo $this->formRow($formPatient->get('tel'));
        echo $this->formRow($formPatient->get('pesel'));
        
       
    }
    if($formPhysician)
    {
        echo $this->formRow($formPhysician->get('npwz'));
    }
   echo $this->formRow($form->get('verified'));
   echo $this->formRow($form->get('submit'));


echo $this->form()->closeTag($form);

