<table class="table">
    <tr>
        <th>Imię</th>        
        <th>Nazwisko</th>       
        <th>Login</th>
        <th>Email</th>
        <th>Typ konta</th>
        <th>Aktywny</th>
        <th>Opracje</th>
    </tr>
    <tr>
        <td><input class="form-control" type="text" id="nameS"></td>
        <td><input class="form-control" type="text" id="surnameS"></td>
        <td><input class="form-control" type="text" id="loginS"></td>
        <td><input class="form-control" type="text" id="emailS"></td>
        <td>
            <select class="form-control warning">
                <option>Administrator</option>
                <option>Lekarz</option>
                <option>Pacjent</option>
                <option>Rejestratorka</option>
            
            </select>
        </td>
        <td >
            <select class="form-control">
                <option>Tak</option>
                <option>Nie</option>
            </select>
        </td>
        
    </tr>
    <?php if($session->role !=2 && $session->role !=3) :?>
    <?php foreach ($users as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->name) ;?></td>
        <td><?php echo $this->escapeHtml($user->surname) ;?></td>
        <td><?php echo $this->escapeHtml($user->login) ;?></td>
        <td><?php echo $this->escapeHtml($user->email) ;?></td>

        <?php if($user->role == 1): ?>
            <td>Administrator</td>
        <?php elseif($user->role == 2): ?>
            <td>Pacjent</td>
        <?php elseif($user->role == 3): ?>
            <td>Lekarz</td>
        <?php elseif($user->role == 4): ?>
            <td>Rejestratorka</td>
        <?php endif;?>        
        <?php if($user->verified == 1) :?>
            <td>TAK</td>
        <?php elseif($user->verified == 0) :?>
            <td>NIE</td>
        <?php endif;?>
        <td>
           <a href="<?php echo $this->url('user',
             array('action'=>'edit', 'id' => $user->id));?>">Edytuj</a>    
            <a href="<?php echo $this->url('user',
             array('action'=>'delete', 'id' => $user->id));?>">Usuń</a>  
            <?php if($user->verified == 1) :?>
            <a href="<?php echo $this->url('user',
             array('action'=>'block', 'id' => $user->id));?>">Blokuj</a> 
            <?php endif;?>
            <?php if($user->verified == 0) :?>
                 <a href="<?php echo $this->url('user',
             array('action'=>'active', 'id' => $user->id));?>">Aktywuj</a>  
            <?php endif;?>
            

     </td>
    </tr>
    <?php endforeach; ?>
    <?php else : ?>
    <tr>
        <td><?php echo $this->escapeHtml($users->name) ;?></td>
        <td><?php echo $this->escapeHtml($users->surname) ;?></td>
        <td><?php echo $this->escapeHtml($users->login) ;?></td>
        <td><?php echo $this->escapeHtml($users->email) ;?></td>
        <td><?php echo $this->escapeHtml($users->role) ;?></td>
        <td><?php echo $this->escapeHtml($users->verified) ;?></td>
        
        <td>
           <a href="<?php echo $this->url('user',
             array('action'=>'edit', 'id' => $users->id));?>">Edytuj</a>    
            
     </td>
    </tr>
    <?php endif; ?>
</table>
<script>
$(document).ready(function() {
    $('#nameS').keyup(function(){
        console.log($(this).val());
        $.ajax({
        type: "POST",
        url: "/ajax/listName",
         dataType : 'json',
        data: {
            name: $(this).val()
        },
        success: function(json) {
            jQuery.each(json, function(i, ob) {
            console.log(i, ob);
        });
        },
        complete: function() {
            $("#loading").hide();
        },
        error: function() {
            console.log( "Wystąpił błąd w połączniu :(");
        }
    });
    });
    $('#surnameS').keyup(function(){
        console.log($(this).val());
        $.ajax({
        type: "POST",
        url: "/ajax/listSurname",
         dataType : 'json',
        data: {
            surname: $(this).val()
        },
        success: function(jsonData) {
                        var json = $.parseJSON(jsonData);
            $(json).each(function(i,val){
                $.each(val,function(k,v){
                      //console.log(k+" : "+ v);     
                      console.log(k);
            });
            });
            },
        complete: function() {
            $("#loading").hide();
        },
        error: function() {
            console.log( "Wystąpił błąd w połączniu :(");
        }
    });
    });
});
    
</script>


