<div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-search" aria-hidden="true" name="physician_id"></span> Blok wyszukiwania </div>
            <div class="panel-body">
               <?php

              echo $this->form()->openTag($form);
              echo $this->formRow($form->get('name'));
              echo $this->formRow($form->get('surname'));
              echo $this->formRow($form->get('login'));
              echo $this->formRow($form->get('email'));
              echo $this->formRow($form->get('submit'));

              
              ?>
            </div>

        </div>
    </div>
<? if($this->role == 1) :?>
<div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-search" aria-hidden="true" name="physician_id"></span> Blok filtrów</div>
            <div class="panel-body">
               <?php
             
              echo $this->formRow($form->get('role'));             
              echo $this->formRow($form->get('verified'));
              echo $this->formRow($form->get('submit'));
              
              
              ?>
            </div>

        </div>
</div>
<?endif;?>
<div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-search" aria-hidden="true" name="physician_id"></span> Blok sortowania</div>
            <div class="panel-body">
               <?php
             
              echo $this->formRow($form->get('sort'));             
              echo $this->formRow($form->get('submit'));
              
              echo $this->form()->closeTag($form);
              ?>
            </div>

        </div>
</div>
<table class="table">
    <tr>
        <th>Imię</th>        
        <th>Nazwisko</th>       
        <th>Login</th>
        <th>Email</th>
        <th>Typ konta</th>
        <th>Aktywny</th>
        <th>Opracje</th>
    </tr>

    <?php if($session->role !=2 && $session->role !=3) :?>
    <?php foreach ($users as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->name) ;?></td>
        <td><?php echo $this->escapeHtml($user->surname) ;?></td>
        <td><?php echo $this->escapeHtml($user->login) ;?></td>
        <td><?php echo $this->escapeHtml($user->email) ;?></td>

        <?php if($user->role == 1): ?>
            <td>Administrator</td>
        <?php elseif($user->role == 2): ?>
            <td>Pacjent</td>
        <?php elseif($user->role == 3): ?>
            <td>Lekarz</td>
        <?php elseif($user->role == 4): ?>
            <td>Rejestratorka</td>
        <?php endif;?>        
        <?php if($user->verified == 1) :?>
            <td>TAK</td>
        <?php elseif($user->verified == 0) :?>
            <td>NIE</td>
        <?php endif;?>
        <td>
           <a href="<?php echo $this->url('user',
             array('action'=>'edit', 'id' => $user->id));?>">Edytuj</a>    
            <?php if ($this->session->role == 1) :?>
            <a href="<?php echo $this->url('user',
             array('action'=>'delete', 'id' => $user->id));?>">Usuń</a> 
                <?php if($user->verified == 1) :?>
                    <a href="<?php echo $this->url('user',
                     array('action'=>'block', 'id' => $user->id));?>">Blokuj</a> 
                     <?php else : ?>
                    <a href="<?php echo $this->url('user',
                   array('action'=>'active', 'id' => $user->id));?>">Aktywuj</a>  
                <?php endif;?>
            <?php endif ;?>             
            
         
            

     </td>
    </tr>
    <?php endforeach; ?>
    <?php else : ?>
    <tr>
        <td><?php echo $this->escapeHtml($users->name) ;?></td>
        <td><?php echo $this->escapeHtml($users->surname) ;?></td>
        <td><?php echo $this->escapeHtml($users->login) ;?></td>
        <td><?php echo $this->escapeHtml($users->email) ;?></td>
        <td><?php echo $this->escapeHtml($users->role) ;?></td>
        <td><?php echo $this->escapeHtml($users->verified) ;?></td>
        
        <td>
           <a href="<?php echo $this->url('user',
             array('action'=>'edit', 'id' => $users->id));?>">Edytuj</a>    
            
     </td>
    </tr>
    <?php endif; ?>
</table>
<script>
$(document).ready(function() {
    $('#nameS').keyup(function(){
        console.log($(this).val());
        $.ajax({
        type: "POST",
        url: "/ajax/listName",
         dataType : 'json',
        data: {
            name: $(this).val()
        },
        success: function(json) {
            jQuery.each(json, function(i, ob) {
            console.log(i, ob);
        });
        },
        complete: function() {
            $("#loading").hide();
        },
        error: function() {
            console.log( "Wystąpił błąd w połączniu :(");
        }
    });
    });
    $('#surnameS').keyup(function(){
        console.log($(this).val());
        $.ajax({
        type: "POST",
        url: "/ajax/listSurname",
         dataType : 'json',
        data: {
            surname: $(this).val()
        },
        success: function(jsonData) {
                        var json = $.parseJSON(jsonData);
            $(json).each(function(i,val){
                $.each(val,function(k,v){
                      //console.log(k+" : "+ v);     
                      console.log(k);
            });
            });
            },
        complete: function() {
            $("#loading").hide();
        },
        error: function() {
            console.log( "Wystąpił błąd w połączniu :(");
        }
    });
    });
});
    
</script>


