<?php 
$this->session = new \Zend\Session\Container('login');

?>
<style>
    .completed {
        background-color: #9d9d9d;
    }
    .waiting {
        background-color: #269abc;
    }    
    tr td a:last-of-type {
        color: #000 !important;

        
    }
</style>
<table class="table">
    <caption>Lista zaplanowanych wizyt</caption>
    <tr>
        <td colspan="5" style="text-align: right">
            <a href="<?php echo $this->url('pdf')?>">
                <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
            </a>
        </td>
    </tr>
    <tr>
        
        <th>id</th>
        <th>Pacjent</th>
        <th>Lekarz</th>
        <th>Data wizyty</th> 
        <? if($this->session->role == 3) :?>
        <th>Zrealizowana</th>
        <? endif; ?>
        <th>Operacje</th>

    </tr>
    
<?php foreach($result as $val) : ?>
    <tr <? ($val['completed']) ? print('class="completed"') : print('class="waiting"') ?>>
        <td><?php echo $val['id']?></td>
        <td><?php echo $val['patient']?></td>
        <td><?php echo $val['physician']?></td>
        <td><?php echo $val['visit_date']?></td>
        <?if($this->session->role != 3) :?>       
        <td>
            <? if($val['completed']) :?>
                Zakończona
            <? else :?>
             <a href="<?php echo $this->url('registration',
             array('action'=>'cancel', 'param' => $val['id']));?>">Odwołaj</a> 
            <? endif;?>
        </td>
        <? elseif($this->session->role == 3) :?>
         <td>
            <?  ($val['completed']) ? print($val['completed']) : print('NIE') ?>
        </td>
        <td>
            <? if(!$val['completed']) :?>
             <a href="<?php echo $this->url('registration',
             array('action'=>'completed', 'param' => $val['id']));?>">Zrealizowana</a>            
            <? else :?>
                Zakończona
            <? endif; ?>
        </td>
        <?endif ;?>
    </tr>
<?php endforeach; ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-search" aria-hidden="true" name="physician_id"></span> Blok filtrów</div>
            <div class="panel-body">
              <?php
              echo $this->form()->openTag($form);
              echo $this->formRow($form->get('patient'));
              if($this->session->role != 3)
              {
                  echo $this->formRow($form->get('physician'));
              }              
              echo $this->formRow($form->get('date'));
              echo $this->formRow($form->get('submit'));
              echo $this->form()->closeTag($form);
              ?>
            </div>

        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span> Blok sortowania </div>
            <div class="panel-body">
            <?php
              echo $this->form()->openTag($form);
              echo $this->formRow($order->get('order'));             
              echo $this->formRow($order->get('submit'));
              echo $this->form()->closeTag($form);
              ?>
            </div>

        </div>
    </div>
</table>