<div class="row">
    <div class="col-md-6">
        <h1>Oszczędzamy Twój czas!</h1>
    <h2>Skorzystaj z elektronicznej rejestracji!</h2>
    <h3>Lekarz Pierwszego Kontaktu</h3>
    </div>
    <div class="col-md-6">
        <h2>UWAGA!!!</h2>   
        <ol>
            <li>W celu rejestracji do lekarza należy założyć konto w systemie www.super-med.pl, podając prawidłowe dane wymagane do utworzenia konta,
prawidłowy i używany adres E-Mail, na który wysyłane są automatycznie wiadomości dla pacjenta,</li>
            <li>Nie ma możliwości tworzenia kilku kont za pomocą jednego adresu e-mail oraz tego samego numeru PESEL.</li>
            <li>Podczas tworzenia konta zostaje wysyłany automatycznie link aktywacyjny w celu weryfikacji użytkownika. Konto należy potwierdzić klikając w link aktywacyjny. W przypadku nie otrzymania linku prosimy sprawdzić folder SPAM,</li>
            <li>Jeżeli przy próbie rejestracji do systemu wyskoczy informacja - "Podany PESEL już istnieje!" , proszę udać się do przychodni w celu przeprowadzenia identyfikacji pacjenta na podstawie dokumentu tożsamości. Ty samym do konta o podanym numerze PESEL zostanie przypisane konto e-mail oraz jednorazowo zostanie nadane hasło.</li>
            <li>W razie problemów z działaniem portalu prosimy o kontakt z administratorem portalu super-med.pl poprzez e-mail:<a href="mailto:rejestracja@super-med.pl">rejestracja@super-med.pl</a> .</li>
        </ol>
    </div>
    
</div>

<div class="row">
    <div class="col-md-12">
        <img class="img-responsive" src="<?php echo $this->basePath('img/kolejka.jpg')?>" alt="banner" style="width: 100%">
    </div>
</div>
<style>
    ol li {
        text-align: justify;
    }
    h1 {
       color:#0E2BA5;
       font-weight: bolder;
       margin-bottom: 0.5em;
    }
    
    h2 {
        text-align: right;
       
        color:#0E2BA5;
        margin-left: 2em;
        margin-bottom: 1.5em;
    }
    
    h3 {
        text-align: right;
        font-size:xx-large;
        color:#0E2BA5;
        font-weight: bolder;
    }
    
    img {
        border-radius: 5px;
        -webkit-box-shadow: 16px 10px 19px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 16px 10px 19px 0px rgba(0,0,0,0.75);
box-shadow: 16px 10px 19px 0px rgba(0,0,0,0.75);
    }
    
</style>