
    <div class="col-md-12">
        <h2>UWAGA!!!</h2>   
        <ol>
            <li>W celu rejestracji do lekarza należy założyć konto w systemie www.super-med.pl, podając prawidłowe dane wymagane do utworzenia konta, prawidłowy i używany adres<br /> E-Mail, na który wysyłane są automatycznie wiadomości dla pacjenta,</li>
            <li>Nie ma możliwości tworzenia kilku kont za pomocą jednego adresu e-mail oraz tego samego numeru PESEL.</li>
            <li>Podczas tworzenia konta zostaje wysyłany automatycznie link aktywacyjny w celu weryfikacji użytkownika. Konto należy potwierdzić klikając w link aktywacyjny. W przypadku nie otrzymania linku prosimy sprawdzić folder SPAM,</li>
            <li>Jeżeli przy próbie rejestracji do systemu wyskoczy informacja - "Podany PESEL już istnieje!" , proszę udać się do przychodni w celu przeprowadzenia identyfikacji pacjenta na podstawie dokumentu tożsamości. Ty samym do konta o podanym numerze PESEL zostanie przypisane konto e-mail oraz jednorazowo zostanie nadane hasło.</li>
            <li>W razie problemów z działaniem portalu prosimy o kontakt z administratorem portalu super-med.pl poprzez e-mail:<a href="mailto:rejestracja@super-med.pl">rejestracja@super-med.pl</a> .</li>
        </ol>
    </div>


<style type="text/css">
   ol li {
        text-align: justify;
        padding-bottom: 15px;
    }
</style>
