<div class="row">
    <div class='col-md-12'>
        <h1>Regulamin erejestracja</h1>
        <p>
        Super-med mieszczący się w Katowicach, udostępnia pacjentom, poza tradycyjnymi kanałami, dodatkową możliwość zarejestrowania się drogą elektroniczną. Regulamin określa warunki oraz zasady obowiązujące wszystkich użytkowników korzystających z systemu super-med.pl.
        </p>
        <h2>Informacje ogólne</h2>
        <p>
            Serwis super-med.pl, zwany dalej „eRejestracja” jest udostępniona osobom zainteresowanym uzyskaniem świadczeń medycznych w SUPER-MED Katowice.
eRejestracja służy zainteresowanym osobom do ustalania, a w razie konieczności także do odwoływania terminów udzielania na ich rzecz świadczeń medycznych w SUPER-MED Katowice, bez konieczności dokonywania tych czynności osobiście lub telefonicznie.
Korzystanie z eRejestracji jest całkowicie bezpłatne.
Administratorem eRejestracji jest SUPER-MED Katowice.
System elektronicznej rejestracji znajduje się pod adresem: http://www.super-med.pl .
Dostęp do systemu eRejestracja przyznawany jest na czas nieokreślony.
Pacjent może dokonać tylko jednej rezerwacji terminu do poradni a kolejną w dzień wizyty lub w dniach następnych.
Pacjent może odwołać wyznaczony termin za pomocą systemu erejestracja, osobiście lub telefonicznie .
Pacjent, który nie może stawić się na wizytę w wyznaczonym terminie zobowiązany jest do odwołania wizyty za pomocą systemu erejestracja lub telefonicznie.

SUPER-MED Katowice zastrzega sobie prawo do zablokowania konta w usłudze eRejestracji w przypadku:
        <ul>
            <li>nieprzestrzegania niniejszego regulaminu,</li>
            <li>jeśli pacjent nie pojawił się na dwóch wizytach zarezerwowanych za pomocą systemu eRejestracji, a wcześniej ich nie odwołał,</li>
        </ul>

SUPER-MED Katowice zastrzega sobie prawo do zmiany harmonogramów pracy poradni o czym użytkownik zostanie powiadomiony drogą elektroniczną lub sms-em.
Wszelkie ewentualne zmiany treści regulaminu zostaną opublikowane na stronie internetowej <a href='www.super-med.pl'>www.super-med.pl</a> . W przypadku braku akceptacji nowych postanowień użytkownik zobowiązuje się do złożenia pisemnego wniosku o zaprzestanie korzystania z systemu.
Prawidłowość danych wprowadzonych przez Użytkownika do eRejestracji spoczywa na nim samym.
Korzystanie z eRejestracji nie może naruszać niniejszego regulaminu oraz powszechnie obowiązujących przepisów prawa.
Administrator ma prawo badać sposób użytkowania eRejestracji oraz blokować lub usuwać Użytkowników niestosujących się do regulaminu serwisu.
        </p>
        <h2>Ochrona i przetwarzanie danych</h2>
        <p>
            Użytkownik jest zobowiązany do zabezpieczenia otrzymanego loginu i hasła przed wglądem osób trzecich.
Administrator nie odpowiada za ujawnienie hasła lub loginu, a także innych informacji wprowadzonych przez użytkownika do eRejestracji niepowołanej osobie, jeżeli Użytkownik nie zabezpieczył ich przed wglądem osób trzecich.
Osoba/użytkownik korzystająca z systemu erejestracja zgadza się na wykorzystanie jej danych osobowych zgodnie z wymogami ustawy z dn. 29 sierpnia 1997 roku o ochronie danych osobowych (Dz.U. 2002 r., Nr 101, poz. 926, z późn. zmianami) przez „SUPER-MED Katowice” w celach rejestracyjnych, jak również promocyjnych i marketingowych usług własnych oraz na otrzymywanie sms. Dane te będą wykorzystane tylko przez „SUPER-MED Katowice” i nie zostaną przekazane w żaden sposób osobom, czy podmiotom trzecim.
Osoba/użytkownik korzystająca z systemu erejestracja „SUPER-MED Katowice” ma prawo w każdym momencie do wglądu w swoje dane, ich zmienianie jak również usunięcie – przy czym usunięcie swoich danych z systemu e-rejestracja skutkuje brakiem możliwości korzystania z eRejestracji.
        </p>
        <h2>Ograniczenie odpowiedzialności</h2>
        <p>
            Administrator dołożył wszelkich możliwych starań, aby zapewnić eRejestracji jak najwyższą jakość użytkowania.
Administrator nie ponosi odpowiedzialności za przerwy w udostępnianiu eRejestracji wynikające z przyczyn niezależnych od niego i za jakiekolwiek szkody, w tym też pośrednie wynikające z przerwy w funkcjonowaniu serwisu wywołane koniecznością konserwacji systemu lub czynnikami niezależnymi od Administratora.
        </p>
        <h2>Informacje techniczne</h2>
        <p>
            Aby e-Rejestracja działała prawidłowo na komputerze Użytkownika, powinna być zainstalowana dowolna przeglądarka internetowa.
Za prawidłową konfigurację przeglądarki odpowiedzialny jest Użytkownik we własnym zakresie.
Zastrzega się przerwy techniczne w działaniu eRejestracji. Ich częstotliwość oraz czas trwania uzależniony jest od potrzeb technicznych.
Zastrzega się prawo do zaprzestania prowadzenia eRejestracji lub usług jej dotyczących w każdym czasie bez powiadomienia.
Administrator może zmienić niniejszy regulamin w każdym czasie.
Zmiany regulaminu obowiązują od chwili ich publikacji w eRejestracji lub w inny wskazanym terminie.

Pełna instrukcja obsługi/tworzeniu konta eRejestracji dostępna jest na stronie.
        </p>
    </div>
</div>
<style type="text/css">
    p {
        text-align: justify;
    }
    h2 {
        font-weight: bold;
    }
</style>